import jsPDF from 'jspdf';

export function generatePDF({ title, subtitle, sections, disclaimer }) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Header bar
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 0, pageW, 56, 'F');

  // Logo text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('HealthHelper', margin, 36);

  y = 80;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(26, 26, 26);
  doc.text(title, margin, y);
  y += 24;

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(107, 114, 128);
    const subLines = doc.splitTextToSize(subtitle, contentW);
    doc.text(subLines, margin, y);
    y += subLines.length * 14 + 8;
  }

  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(1);
  doc.line(margin, y, pageW - margin, y);
  y += 20;

  // Sections
  sections.forEach(section => {
    if (y > 680) {
      doc.addPage();
      y = margin;
    }

    // Section heading
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(249, 115, 22);
    doc.text(section.heading, margin, y);
    y += 18;

    // Section content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(26, 26, 26);
    const lines = doc.splitTextToSize(section.content, contentW);
    lines.forEach(line => {
      if (y > 700) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 15;
    });
    y += 14;
  });

  // Disclaimer
  if (disclaimer) {
    if (y > 660) { doc.addPage(); y = margin; }
    doc.setDrawColor(229, 231, 235);
    doc.line(margin, y, pageW - margin, y);
    y += 14;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(156, 163, 175);
    const dLines = doc.splitTextToSize(disclaimer, contentW);
    doc.text(dLines, margin, y);
  }

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by HealthHelper — healthhelper.app', margin, doc.internal.pageSize.getHeight() - 20);

  return doc;
}

export function downloadPDF(doc, filename) {
  doc.save(filename);
}